spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BeyzaGonculer/4.5-library-project
          default-label: main
          search-paths:
            - configurations/
            - configurations/{application}
server:
  port: 8787
